//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputSystem/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""2d81da4d-ce47-4c42-bdd1-280933861a39"",
            ""actions"": [
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""8d7bc408-bf2c-4cbe-bf0b-052a0033d136"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""a2c3cef8-6a65-4c13-9a19-646391fe8c11"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Equip"",
                    ""type"": ""Button"",
                    ""id"": ""1350ec64-7bdb-40e4-aed2-b041dea672c0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Stab"",
                    ""type"": ""Button"",
                    ""id"": ""28d06adb-49ef-42fc-9270-8a9595e78931"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""ef80e701-61f8-4af0-920d-a08ed042fd6a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""b55516ef-063f-4422-a799-594e30f73623"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""ba55cee0-1823-4d49-a09d-c9fee198c73f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Inventory"",
                    ""type"": ""Button"",
                    ""id"": ""6c8d842c-5f67-4cbe-b562-194f7496ab51"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CloseInventory"",
                    ""type"": ""Button"",
                    ""id"": ""b89643c9-cd95-414e-a3a0-b7f5926a708c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InteractDoor"",
                    ""type"": ""Button"",
                    ""id"": ""744b95cc-6894-4a34-a272-3e5fc80e1c92"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ExitChair"",
                    ""type"": ""Button"",
                    ""id"": ""362986c7-ce02-4607-bd67-af14855b1632"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenCamera"",
                    ""type"": ""Button"",
                    ""id"": ""b986b7e2-7f1d-455f-8bd4-c9d260f0eeef"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DismissDialogue"",
                    ""type"": ""Button"",
                    ""id"": ""1a4a7c28-e18b-40c8-9cca-840253ca191b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TakePhoto"",
                    ""type"": ""Button"",
                    ""id"": ""15af8378-9077-4d27-b740-731718ce01ba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ExitCamera"",
                    ""type"": ""Button"",
                    ""id"": ""39de8801-fe2b-49f4-8fc3-535e2d5ca8d2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Swing"",
                    ""type"": ""Button"",
                    ""id"": ""690bb63e-5c16-42cf-a266-eff65d337704"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Repair"",
                    ""type"": ""Button"",
                    ""id"": ""2a012985-4a31-472c-a0a0-adad13ea1016"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ControlPanel"",
                    ""type"": ""Button"",
                    ""id"": ""2de8ece5-07f1-4bd9-8efe-74a1fd1c0ae1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mouse_Down"",
                    ""type"": ""Button"",
                    ""id"": ""49bcf379-467e-42cc-9690-26282272d7f1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mouse_Up"",
                    ""type"": ""Button"",
                    ""id"": ""b4eb9c46-bbc6-44b2-9001-0830dd3e129a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleCursor"",
                    ""type"": ""Button"",
                    ""id"": ""88d98e5f-2f4a-45d0-9fe2-2defbde3283c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e1fd21aa-c993-4b89-b7c3-bc61afb60e8f"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7fe7e887-6238-463a-9532-652a2353fbd8"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""258e3729-fd06-4316-8b8a-bb2dc8e2bf01"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Equip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4d8a5ea-27e9-40a6-a2f7-70c01c33c36e"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f223b3a-44a2-426c-88b9-47f4269cb990"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Arrow keys"",
                    ""id"": ""db287866-e7ea-4d08-8890-db081c059148"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6a236104-84e6-4d96-a732-c92319335558"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b5ba7d8d-9872-4870-b259-4c87c02f2dd4"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""af75d179-964d-4414-93b0-4ae03cbf2422"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""04c1374b-cdbf-4dc6-9ade-bedc06e376a3"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""0a5c83f5-bb56-4350-b97d-9c2351eb5af5"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""70fe8347-7dd2-41ea-a5ee-d34a3fe904da"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b27cf76c-5bd3-4d34-bd5a-7b0dafef6c6a"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""cde424c1-97f2-4607-8dd0-9f53ed54ee85"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""71b97744-3c9f-4dd9-90a1-53cf1a17e531"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""16b587c6-c252-4488-82f4-c46cd225466e"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""974b3295-9602-442c-bc44-ec1fcd0082a1"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5a8f701d-acb8-43ed-8254-922ceb2d031d"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f87e713a-7601-4a36-9fae-e60c4b3aed20"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InteractDoor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b1fd619-1dc3-458a-824a-11fcbb7e3442"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ExitChair"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a0fd6229-be60-4ff3-a678-e3044ac155da"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a5cd401e-7a91-483f-aa96-b79e3b8faa8a"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DismissDialogue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""39306750-8222-4642-820b-e8d021a65843"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TakePhoto"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bca27b08-a350-44d0-9f32-16d52447ba5c"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ExitCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""658200db-34bd-4be7-87f1-1fc89bbd53ce"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Swing"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""23cbc53d-0690-4e27-b4e6-2951514d2c42"",
                    ""path"": ""<Keyboard>/#(R)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Repair"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c4dd282-71ff-41d3-bcb4-de8657f6d517"",
                    ""path"": ""<Keyboard>/#(A)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControlPanel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""535f6e02-16d2-42da-8c62-63b1b39dd871"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse_Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35d1d7d4-30c5-4890-85f7-4dfb86e4f146"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse_Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35d6011b-3591-4542-b967-bef19a80ebea"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleCursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Crouch = m_Player.FindAction("Crouch", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_Equip = m_Player.FindAction("Equip", throwIfNotFound: true);
        m_Player_Stab = m_Player.FindAction("Stab", throwIfNotFound: true);
        m_Player_Shoot = m_Player.FindAction("Shoot", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_Look = m_Player.FindAction("Look", throwIfNotFound: true);
        m_Player_Inventory = m_Player.FindAction("Inventory", throwIfNotFound: true);
        m_Player_CloseInventory = m_Player.FindAction("CloseInventory", throwIfNotFound: true);
        m_Player_InteractDoor = m_Player.FindAction("InteractDoor", throwIfNotFound: true);
        m_Player_ExitChair = m_Player.FindAction("ExitChair", throwIfNotFound: true);
        m_Player_OpenCamera = m_Player.FindAction("OpenCamera", throwIfNotFound: true);
        m_Player_DismissDialogue = m_Player.FindAction("DismissDialogue", throwIfNotFound: true);
        m_Player_TakePhoto = m_Player.FindAction("TakePhoto", throwIfNotFound: true);
        m_Player_ExitCamera = m_Player.FindAction("ExitCamera", throwIfNotFound: true);
        m_Player_Swing = m_Player.FindAction("Swing", throwIfNotFound: true);
        m_Player_Repair = m_Player.FindAction("Repair", throwIfNotFound: true);
        m_Player_ControlPanel = m_Player.FindAction("ControlPanel", throwIfNotFound: true);
        m_Player_Mouse_Down = m_Player.FindAction("Mouse_Down", throwIfNotFound: true);
        m_Player_Mouse_Up = m_Player.FindAction("Mouse_Up", throwIfNotFound: true);
        m_Player_ToggleCursor = m_Player.FindAction("ToggleCursor", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Crouch;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_Equip;
    private readonly InputAction m_Player_Stab;
    private readonly InputAction m_Player_Shoot;
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_Look;
    private readonly InputAction m_Player_Inventory;
    private readonly InputAction m_Player_CloseInventory;
    private readonly InputAction m_Player_InteractDoor;
    private readonly InputAction m_Player_ExitChair;
    private readonly InputAction m_Player_OpenCamera;
    private readonly InputAction m_Player_DismissDialogue;
    private readonly InputAction m_Player_TakePhoto;
    private readonly InputAction m_Player_ExitCamera;
    private readonly InputAction m_Player_Swing;
    private readonly InputAction m_Player_Repair;
    private readonly InputAction m_Player_ControlPanel;
    private readonly InputAction m_Player_Mouse_Down;
    private readonly InputAction m_Player_Mouse_Up;
    private readonly InputAction m_Player_ToggleCursor;
    public struct PlayerActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Crouch => m_Wrapper.m_Player_Crouch;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @Equip => m_Wrapper.m_Player_Equip;
        public InputAction @Stab => m_Wrapper.m_Player_Stab;
        public InputAction @Shoot => m_Wrapper.m_Player_Shoot;
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @Look => m_Wrapper.m_Player_Look;
        public InputAction @Inventory => m_Wrapper.m_Player_Inventory;
        public InputAction @CloseInventory => m_Wrapper.m_Player_CloseInventory;
        public InputAction @InteractDoor => m_Wrapper.m_Player_InteractDoor;
        public InputAction @ExitChair => m_Wrapper.m_Player_ExitChair;
        public InputAction @OpenCamera => m_Wrapper.m_Player_OpenCamera;
        public InputAction @DismissDialogue => m_Wrapper.m_Player_DismissDialogue;
        public InputAction @TakePhoto => m_Wrapper.m_Player_TakePhoto;
        public InputAction @ExitCamera => m_Wrapper.m_Player_ExitCamera;
        public InputAction @Swing => m_Wrapper.m_Player_Swing;
        public InputAction @Repair => m_Wrapper.m_Player_Repair;
        public InputAction @ControlPanel => m_Wrapper.m_Player_ControlPanel;
        public InputAction @Mouse_Down => m_Wrapper.m_Player_Mouse_Down;
        public InputAction @Mouse_Up => m_Wrapper.m_Player_Mouse_Up;
        public InputAction @ToggleCursor => m_Wrapper.m_Player_ToggleCursor;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Crouch.started += instance.OnCrouch;
            @Crouch.performed += instance.OnCrouch;
            @Crouch.canceled += instance.OnCrouch;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Equip.started += instance.OnEquip;
            @Equip.performed += instance.OnEquip;
            @Equip.canceled += instance.OnEquip;
            @Stab.started += instance.OnStab;
            @Stab.performed += instance.OnStab;
            @Stab.canceled += instance.OnStab;
            @Shoot.started += instance.OnShoot;
            @Shoot.performed += instance.OnShoot;
            @Shoot.canceled += instance.OnShoot;
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Inventory.started += instance.OnInventory;
            @Inventory.performed += instance.OnInventory;
            @Inventory.canceled += instance.OnInventory;
            @CloseInventory.started += instance.OnCloseInventory;
            @CloseInventory.performed += instance.OnCloseInventory;
            @CloseInventory.canceled += instance.OnCloseInventory;
            @InteractDoor.started += instance.OnInteractDoor;
            @InteractDoor.performed += instance.OnInteractDoor;
            @InteractDoor.canceled += instance.OnInteractDoor;
            @ExitChair.started += instance.OnExitChair;
            @ExitChair.performed += instance.OnExitChair;
            @ExitChair.canceled += instance.OnExitChair;
            @OpenCamera.started += instance.OnOpenCamera;
            @OpenCamera.performed += instance.OnOpenCamera;
            @OpenCamera.canceled += instance.OnOpenCamera;
            @DismissDialogue.started += instance.OnDismissDialogue;
            @DismissDialogue.performed += instance.OnDismissDialogue;
            @DismissDialogue.canceled += instance.OnDismissDialogue;
            @TakePhoto.started += instance.OnTakePhoto;
            @TakePhoto.performed += instance.OnTakePhoto;
            @TakePhoto.canceled += instance.OnTakePhoto;
            @ExitCamera.started += instance.OnExitCamera;
            @ExitCamera.performed += instance.OnExitCamera;
            @ExitCamera.canceled += instance.OnExitCamera;
            @Swing.started += instance.OnSwing;
            @Swing.performed += instance.OnSwing;
            @Swing.canceled += instance.OnSwing;
            @Repair.started += instance.OnRepair;
            @Repair.performed += instance.OnRepair;
            @Repair.canceled += instance.OnRepair;
            @ControlPanel.started += instance.OnControlPanel;
            @ControlPanel.performed += instance.OnControlPanel;
            @ControlPanel.canceled += instance.OnControlPanel;
            @Mouse_Down.started += instance.OnMouse_Down;
            @Mouse_Down.performed += instance.OnMouse_Down;
            @Mouse_Down.canceled += instance.OnMouse_Down;
            @Mouse_Up.started += instance.OnMouse_Up;
            @Mouse_Up.performed += instance.OnMouse_Up;
            @Mouse_Up.canceled += instance.OnMouse_Up;
            @ToggleCursor.started += instance.OnToggleCursor;
            @ToggleCursor.performed += instance.OnToggleCursor;
            @ToggleCursor.canceled += instance.OnToggleCursor;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Crouch.started -= instance.OnCrouch;
            @Crouch.performed -= instance.OnCrouch;
            @Crouch.canceled -= instance.OnCrouch;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Equip.started -= instance.OnEquip;
            @Equip.performed -= instance.OnEquip;
            @Equip.canceled -= instance.OnEquip;
            @Stab.started -= instance.OnStab;
            @Stab.performed -= instance.OnStab;
            @Stab.canceled -= instance.OnStab;
            @Shoot.started -= instance.OnShoot;
            @Shoot.performed -= instance.OnShoot;
            @Shoot.canceled -= instance.OnShoot;
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Inventory.started -= instance.OnInventory;
            @Inventory.performed -= instance.OnInventory;
            @Inventory.canceled -= instance.OnInventory;
            @CloseInventory.started -= instance.OnCloseInventory;
            @CloseInventory.performed -= instance.OnCloseInventory;
            @CloseInventory.canceled -= instance.OnCloseInventory;
            @InteractDoor.started -= instance.OnInteractDoor;
            @InteractDoor.performed -= instance.OnInteractDoor;
            @InteractDoor.canceled -= instance.OnInteractDoor;
            @ExitChair.started -= instance.OnExitChair;
            @ExitChair.performed -= instance.OnExitChair;
            @ExitChair.canceled -= instance.OnExitChair;
            @OpenCamera.started -= instance.OnOpenCamera;
            @OpenCamera.performed -= instance.OnOpenCamera;
            @OpenCamera.canceled -= instance.OnOpenCamera;
            @DismissDialogue.started -= instance.OnDismissDialogue;
            @DismissDialogue.performed -= instance.OnDismissDialogue;
            @DismissDialogue.canceled -= instance.OnDismissDialogue;
            @TakePhoto.started -= instance.OnTakePhoto;
            @TakePhoto.performed -= instance.OnTakePhoto;
            @TakePhoto.canceled -= instance.OnTakePhoto;
            @ExitCamera.started -= instance.OnExitCamera;
            @ExitCamera.performed -= instance.OnExitCamera;
            @ExitCamera.canceled -= instance.OnExitCamera;
            @Swing.started -= instance.OnSwing;
            @Swing.performed -= instance.OnSwing;
            @Swing.canceled -= instance.OnSwing;
            @Repair.started -= instance.OnRepair;
            @Repair.performed -= instance.OnRepair;
            @Repair.canceled -= instance.OnRepair;
            @ControlPanel.started -= instance.OnControlPanel;
            @ControlPanel.performed -= instance.OnControlPanel;
            @ControlPanel.canceled -= instance.OnControlPanel;
            @Mouse_Down.started -= instance.OnMouse_Down;
            @Mouse_Down.performed -= instance.OnMouse_Down;
            @Mouse_Down.canceled -= instance.OnMouse_Down;
            @Mouse_Up.started -= instance.OnMouse_Up;
            @Mouse_Up.performed -= instance.OnMouse_Up;
            @Mouse_Up.canceled -= instance.OnMouse_Up;
            @ToggleCursor.started -= instance.OnToggleCursor;
            @ToggleCursor.performed -= instance.OnToggleCursor;
            @ToggleCursor.canceled -= instance.OnToggleCursor;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnCrouch(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnEquip(InputAction.CallbackContext context);
        void OnStab(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnInventory(InputAction.CallbackContext context);
        void OnCloseInventory(InputAction.CallbackContext context);
        void OnInteractDoor(InputAction.CallbackContext context);
        void OnExitChair(InputAction.CallbackContext context);
        void OnOpenCamera(InputAction.CallbackContext context);
        void OnDismissDialogue(InputAction.CallbackContext context);
        void OnTakePhoto(InputAction.CallbackContext context);
        void OnExitCamera(InputAction.CallbackContext context);
        void OnSwing(InputAction.CallbackContext context);
        void OnRepair(InputAction.CallbackContext context);
        void OnControlPanel(InputAction.CallbackContext context);
        void OnMouse_Down(InputAction.CallbackContext context);
        void OnMouse_Up(InputAction.CallbackContext context);
        void OnToggleCursor(InputAction.CallbackContext context);
    }
}
